update ci.yml to debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -23,6 +23,10 @@ jobs:
         working-directory: ./server
         run: npm install
 
+      - name: Check jest exists
+        working-directory: ./server
+        run: ls node_modules/.bin/jest || echo "Jest not found"
+
       - name: Run tests
         working-directory: ./server
         run: npm test
